In [1]:
import openmm as mm
from openmm.app import *
from openmm import *
from openmm.unit import *

In [2]:
pdb = PDBFile('6v3g_silcs.1.pdb')
PeriodicBoxVectors = pdb.topology.getPeriodicBoxVectors()
topo = GromacsTopFile('6v3g_silcs.1.top' , periodicBoxVectors=PeriodicBoxVectors,
                                  includeDir='./')
system = topo.createSystem(nonbondedMethod=CutoffPeriodic, nonbondedCutoff= 2 ,
                                                  constraints=HBonds)
integrator = LangevinMiddleIntegrator(298 * kelvin , 1 / picoseconds, 0.002 * picoseconds)
simulation = Simulation(topo.topology, system, integrator)
simulation.context.setPositions(pdb.positions)
state = simulation.context.getState(getEnergy=True)
print('Initial energy: ', state.getPotentialEnergy())

Initial energy:  67720432.24309993 kJ/mol


In [14]:
pdb = PDBFile('6v3g_silcs.2.pdb')
PeriodicBoxVectors = pdb.topology.getPeriodicBoxVectors()
topo = GromacsTopFile('6v3g_silcs.2.top' , periodicBoxVectors=PeriodicBoxVectors,
                                  includeDir='./')
system = topo.createSystem(nonbondedMethod=CutoffPeriodic, nonbondedCutoff= 1.5 ,
                                                  constraints=HBonds)
integrator = LangevinMiddleIntegrator(298 * kelvin , 1 / picoseconds, 0.002 * picoseconds)
simulation = Simulation(topo.topology, system, integrator)
simulation.context.setPositions(pdb.positions)
state = simulation.context.getState(getEnergy=True)
print('Initial energy: ', state.getPotentialEnergy())

Initial energy:  67770795.67961206 kJ/mol


In [3]:
pdb = PDBFile('6v3g_silcs.3.pdb')
PeriodicBoxVectors = pdb.topology.getPeriodicBoxVectors()
topo = GromacsTopFile('6v3g_silcs.3.top' , periodicBoxVectors=PeriodicBoxVectors,
                                  includeDir='./')
system = topo.createSystem(nonbondedMethod=CutoffPeriodic, nonbondedCutoff= 2 ,
                                                  constraints=HBonds)
integrator = LangevinMiddleIntegrator(298 * kelvin , 1 / picoseconds, 0.002 * picoseconds)
simulation = Simulation(topo.topology, system, integrator)
simulation.context.setPositions(pdb.positions)
state = simulation.context.getState(getEnergy=True)
print('Initial energy: ', state.getPotentialEnergy())

Initial energy:  67720064.1905509 kJ/mol


In [16]:
67770795.67961206 - 67758683.8041696

12111.87544246018

In [3]:
67758547.67961206 - 67758683.8041696

-136.12455753982067

In [5]:
67720064.1905509 - 67720432.24309993

-368.05254903435707

In [19]:
import numpy as np

# Define the vector to be rotated, rotation axis and the angle
v = np.array([0.000, 0.000, -0.391])
k = np.array([29.850, 42.018, 155.751])
theta = 0.847

# Normalize k
k_norm = k / np.linalg.norm(k)

# Compute rotated vector
v_rot = v*np.cos(theta) + np.cross(k_norm, v)*np.sin(theta) + k_norm*np.dot(k_norm, v)*(1 - np.cos(theta))

print(v_rot)

[-0.09784862  0.02119442 -0.37796487]


In [20]:

# Define the rotation axis and the angle
k = np.array([29.850, 42.018, 155.751])
theta = 0.847

# Normalize k
k_norm = k / np.linalg.norm(k)

# Define the skew-symmetric matrix K
K = np.array([[0, -k_norm[2], k_norm[1]], 
              [k_norm[2], 0, -k_norm[0]], 
              [-k_norm[1], k_norm[0], 0]])

# Define the identity matrix
I = np.eye(3)

# Compute rotation matrix
R = I + np.sin(theta) * K + (1 - np.cos(theta)) * np.dot(K, K)

print(R)

[[ 0.67341581 -0.69561841  0.25025221]
 [ 0.72709826  0.68439014 -0.05420567]
 [-0.13356368  0.21846091  0.96666208]]


Initial energy:  67758747.8041696 kJ/mol
